### ISSUE TITLE
consentForm.load(); NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by yachou31** [appodeal/appodeal-unity-demo#11]

**Comment by KulArtsiom** [comment]
@yachou31 
Hi. Could you tell me which Unity version do you use and which branch appodeal-unity-demo repository? Could you check that your mainTemplate.gradle file include implementation 'com.explorestack:consent:1.0.1' dependency? Also please describe how can I reproduce this exception?

**Comment by yachou31** [comment]
Hi, Unity version is  2019.2.10f1, and I have 'com.explorestack:consent:1.0.1' dependency? Included in the maintemplate.gradle. after I encountered this error in my project I tried to build appodeal's demo project to check if It produces the same error and unfortunately it did too. I also tried both 2.10.6 and 2.11.0 beta sdk versions but nothing changes. 
Thank in advance.

**Comment by KulArtsiom** [comment]
@yachou31 
I think this issue depends on this unity version, I can't reproduce it on 2019.2.21f version. Could you try to reproduce it on this version?

**Comment by yachou31** [comment]
installed 2019.2.21f version and the error is the same 
here is a debug log from android studio when clicking load form button in appodeal demo app :
`E/Unity: AndroidJavaException: java.lang.NoSuchMethodError: no non-static method "Lcom/explorestack/consent/exception/ConsentManagerException;.<init>()V"
    java.lang.NoSuchMethodError: no non-static method "Lcom/explorestack/consent/exception/ConsentManagerException;.<init>()V"
        at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
        at com.unity3d.player.ReflectionHelper.a(Unknown Source)
        at com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source)
        at java.lang.reflect.Proxy.invoke(Proxy.java:813)
        at $Proxy9.onConsentFormError(Unknown Source)
        at com.explorestack.consent.ConsentForm$1.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:6244)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
    	at com.android.internal.os.ZygoteInit.main(Z
`

**Comment by KulArtsiom** [comment]
@yachou31 
Hey! We fixed this issue in 2.10.7 Appodeal plugin version.
